run:
  skip-dirs:
    - vendor
    - pkg/crd

  skip-files:
    # TODO: lint test files as well
    - ".*\\_test.go$"

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nosprintfhostport
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  revive:
    rules:
      # TODO: enable recommended (default) revive rules
      - name: unused-parameter
