run:
  skip-dirs:
    - vendor
    - pkg/crd

  skip-files:
    # TODO: lint test files as well
    - ".*\\_test.go$"

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - importas
    - ineffassign
    - nosprintfhostport
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  
  importas:
    no-unaliased: true
    alias:
      # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
  
  revive:
    rules:
      # TODO: enable recommended (default) revive rules
      - name: duplicated-imports
      - name: error-naming
      - name: unused-parameter
