run:
  skip-dirs:
    - vendor
    - pkg/crd

  skip-files:
    - ".*\\_test.go$"

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nosprintfhostport
    - staticcheck
    - typecheck
    - unused
